apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flaskapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: my-app-flask
          image: chandansingh95/gha-pyapp:da9bda1
          ports:
            - containerPort: 5000
